name: posadmin
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  cloud_firestore: ^4.14.0
  easy_sidemenu: ^0.6.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  go_router: ^14.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  permission_handler: ^11.3.1
  qr_bar_code_scanner_dialog: ^0.0.5
  qr_code_scanner: ^1.0.1

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^7.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
  generate: true
